import { ReactNode } from "react";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";
import { WebGLProvider } from "@/components/ui/BackgroundGradient/WebGLContext";
import YandexMetrika from "@/components/YandexMetrika";

export const metadata: Metadata = {
  title: "СибКомплект",
  description: "Generated by create next app",
  icons: {
    icon: "/цвет.svg",
    shortcut: "/цвет.svg",
    apple: "/цвет.svg",
  },
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <YandexMetrika />
      </head>
      <body>
        <WebGLProvider>
          <Providers>{children}</Providers>
        </WebGLProvider>
      </body>
    </html>
  );
}
