import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { BreakpointIndicator } from "@/components/dev/BreakpointIndicator";
import Navbar from "@/components/sections/Navbar";
import Footer from "@/components/sections/Footer";
import ConditionalBGGradient from "@/components/ui/ConditionalBGGradient";
import LocomotiveScrollProvider from "@/components/providers/LocomotiveScrollProvider";
import MainScene from "@/components/3DScene/main";
import { CameraProvider } from "@/components/3DScene/features/CameraContext";

const inter = Inter({
  subsets: ["cyrillic"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  robots: {
    index: false,
    follow: false,
    nocache: true,
    noarchive: true,
    nosnippet: true,
    noimageindex: true,
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
      <CameraProvider>
        <ConditionalBGGradient />
        
        <MainScene />
        <BreakpointIndicator />
        <Navbar />
        {/* <LocomotiveScrollProvider> */}
        
        {children}
        <Footer />
        {/* </LocomotiveScrollProvider> */}
        </CameraProvider>
      </body>
    </html>
  );
}
